version: '3.8'

services:
  user-service:
    build: ./lab2PRUserService
    ports:
      - "8081:8080"
    networks:
      - app-network

  order-service:
    build: ./lab2PROrderService
    ports:
      - "8082:8080"
    depends_on:
      - user-service
    networks:
      - app-network
    environment:
      - USER_SERVICE_URL=http://user-service:8080/users/

networks:
  app-network:
    driver: bridge
